gif2swf -r 30 -o angry.swf angry.gif 
gif2swf -r 30 -o beer.swf beer.gif 
gif2swf -r 30 -o box.swf box.gif 
gif2swf -r 30 -o bye.swf bye.gif 
gif2swf -r 30 -o confused.swf confused.gif 
gif2swf -r 30 -o cool.swf cool.gif 
gif2swf -r 30 -o crazy.swf crazy.gif 
gif2swf -r 30 -o cry.swf cry.gif 
gif2swf -r 30 -o dance.swf dance.gif 
gif2swf -r 30 -o diablo.swf diablo.gif 
gif2swf -r 30 -o evil.swf evil.gif 
gif2swf -r 30 -o excl.swf excl.gif 
gif2swf -r 30 -o good.swf good.gif 
gif2swf -r 30 -o guns.swf guns.gif 
gif2swf -r 30 -o happy.swf happy.gif 
gif2swf -r 30 -o heart.swf heart.gif 
gif2swf -r 30 -o help.swf help.gif 
gif2swf -r 30 -o hmmm.swf hmmm.gif 
gif2swf -r 30 -o huh.swf huh.gif 
gif2swf -r 30 -o idea.swf idea.gif 
gif2swf -r 30 -o judge.swf judge.gif 
gif2swf -r 30 -o love.swf love.gif 
gif2swf -r 30 -o mml.swf mml.gif 
gif2swf -r 30 -o music.swf music.gif 
gif2swf -r 30 -o nana.swf nana.gif 
gif2swf -r 30 -o no.swf no.gif 
gif2swf -r 30 -o noexpression.swf noexpression.gif 
gif2swf -r 30 -o pratchka.swf pratchka.gif 
gif2swf -r 30 -o punk.swf punk.gif 
gif2swf -r 30 -o ras.swf ras.gif 
gif2swf -r 30 -o rofl.swf rofl.gif 
gif2swf -r 30 -o rolleyes.swf rolleyes.gif 
gif2swf -r 30 -o rtfm.swf rtfm.gif 
gif2swf -r 30 -o sad.swf sad.gif 
gif2swf -r 30 -o secret.swf secret.gif 
gif2swf -r 30 -o sex.swf sex.gif 
gif2swf -r 30 -o sick.swf sick.gif 
gif2swf -r 30 -o skandal.swf skandal.gif 
gif2swf -r 30 -o sleeping.swf sleeping.gif 
gif2swf -r 30 -o sly.swf sly.gif 
gif2swf -r 30 -o smartass.swf smartass.gif 
gif2swf -r 30 -o smile.swf smile.gif 
gif2swf -r 30 -o sorry.swf sorry.gif 
gif2swf -r 30 -o tease.swf tease.gif 
gif2swf -r 30 -o thumbsdown.swf thumbsdown.gif 
gif2swf -r 30 -o unknw.swf unknw.gif 
gif2swf -r 30 -o unsure.swf unsure.gif 
gif2swf -r 30 -o wall.swf wall.gif 
gif2swf -r 30 -o whistle.swf whistle.gif 
gif2swf -r 30 -o wink.swf wink.gif 
gif2swf -r 30 -o yahoo.swf yahoo.gif 
gif2swf -r 30 -o yawn.swf yawn.gif 
gif2swf -r 30 -o yes.swf yes.gif 

