name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  MAVEN_VERSION: 3.9.9

jobs:
  build:

    runs-on: ubuntu-24.04
    strategy:
      matrix:
        java:
        - '21'

    steps:
    - uses: actions/checkout@v6

    - name: Setup Temurin JDK
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: ${{ matrix.java }}

    - name: Apt update
      run: sudo apt update


    - name: Install Maven
      run: |
        wget --retry-connrefused --tries=5 --waitretry=5 --read-timeout=20 --timeout=15 https://archive.apache.org/dist/maven/maven-3/${MAVEN_VERSION}/binaries/apache-maven-${MAVEN_VERSION}-bin.tar.gz
        tar -xzf apache-maven-${MAVEN_VERSION}-bin.tar.gz

    - name: Cache Maven packages
      uses: actions/cache@v5
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2

    - name: Build with Maven
      run: |
        java -version
        ./apache-maven-${MAVEN_VERSION}/bin/mvn --show-version clean verify -PallModules,Jenkins
